### ISSUE TITLE
`vite_rails` doesn't work in dev

### ISSUE THREAD

**Issue by danielma** [danielma/vite-problem-repro#1]
Something about Rollup isn't working correctly with Typescript, `vite_rails`, and `@planningcenter/url` through `@planningcenter/api-client`

## Repro steps:

- `foreman start -f Procfile.dev`
- Open browser to http://localhost:5051/

Here's the console output from this repo at https://github.com/danielma/vite-problem-repro/blob/main/app/javascript/entrypoints/application.ts

<img width="1473" alt="CleanShot 2023-08-29 at 09 35 31@2x" src="https://github.com/danielma/vite-problem-repro/assets/993340/2fdc64bc-9a9b-461f-821b-c4e18d6eee9c">

## What I know

I've gone backwards through the minified source and I'm pretty sure the function that's causing the issue in question is `getAugmentedNamespace` from Rollup's commonjs helpers: https://github.com/rollup/plugins/blob/master/packages/commonjs/src/helpers.js#L37

A couple important things to note:

1. `bin/vite dev` **does** work correctly. I have no idea what's different about that env 😬 
2. As expressed, using `@planningcenter/url` works correctly. There's something weird about using it _through_ `@planningcenter/api-client`. And the issue doesn't appear until you actually call `Client.get`, which is weird. It's _some_ sort of module loading issue, and frankly I'd expect that to be more likely to show up right on first page load

**Comment by kylemellander** [comment]
#### Simple answer

You need to set the commonjs option of `requireReturnsDefault` to either `true`, `auto`, or `preferred`. [link](https://github.com/rollup/plugins/blob/master/packages/commonjs/README.md#requirereturnsdefault)

#### Explanation

Because of the way that `api-client` compiles into commonjs, it interprets:

```typescript
import pcoUrl from "@planningcenter/url"
```

into

```typescript
var a = require("@planningcenter/url")
```

By default, commonjs will then interpret that import as:

```typescript
require("@planningcenter/url")
//  { __esModule: true, default: WhateverTheExportIs }
```

And since the code within the api-client does not call `.default` to find the export, it tries to call the functionality on the wrapper (like the output above) instead of just the default export value.

Updating the setting changes how commonjs interprets those imports.

#### Conclusion

Adding this setting might be enough, but I think this has a little bit of potential to cause issues if anything requires the default setting.  To be safest for this, you can make the value of `requireReturnsDefault` to a function like this:

```typescript
export default defineConfig({
  plugins: [RubyPlugin()],
  build: {
    commonjsOptions: {
      requireReturnsDefault: (importPath) =>
        /@planningcenter\/url\//.test(importPath),
    },
  },
})
```

**Comment by danielma** [comment]
Wow! That did it. Thank you so much!
